### ISSUE TITLE
String operations

### ISSUE THREAD

**Issue by damagedgoods** [chazzdesign/sketch-calculator#10]
Allow operations with strings, not only numbers. Concatenate, substring, uppercase, lowercase...

**Comment by javierarce** [comment]
Here's a proposal for some methods based on the Google Spreadsheet syntax:

`=CONCATENATE(A1,A2,A3)` 
https://support.google.com/docs/answer/3094123?hl=en

`=UPPER(A1)`
https://support.google.com/docs/answer/3094219?hl=en&ref_topic=3105625

`=LOWER(A1)`
https://support.google.com/docs/answer/3094083?hl=en&ref_topic=3105625

**Comment by javierarce** [comment]
In the case of `CONCATENATE` I think we could also allow using `CONCAT`.

**Comment by damagedgoods** [comment]
Perfect.

Now I'm thinking this string idea could get complicated. Things like "={nombre}@{dominio}.com" seem interesting, but maybe it doesn't fit the mathematical model of number & operations we are using. It would be more a template approach.

Does it make sense to manage it the same way, or should be separate plugins?

**Comment by javierarce** [comment]
That's a good point… I think our `CONCAT` method could support the use of strings, so we could write that like:

`=CONCAT({nombre}, '@', {email})`
