### ISSUE TITLE
Define scope of the values

### ISSUE THREAD

**Issue by damagedgoods** [chazzdesign/sketch-calculator#14]
Decide if the name scope is the same artboard as the formula text, or if they should be global.

The first approach is better when you have several copies of a similar artboard on the same page. For example: several versions or variants of the same screen, with different values.

The second approach is better when you want to define a variable globally. For example, define {username} in a single place for all artboards of the page.

Maybe we could consider both through syntax. {value1} looks for "value1" only in the current artboard, {*username} looks for "username" in the whole page.

What do you think, @javierarce ?

**Comment by javierarce** [comment]
I like your last proposal a lot: `{name}` is local, `{*name}` is global.
