### ISSUE TITLE
Test performance in complex document

### ISSUE THREAD

**Issue by damagedgoods** [chazzdesign/sketch-calculator#8]
The current version of the plugin might have a poor performance in complex documents.

**Comment by damagedgoods** [comment]
I'm starting to notice the performance with a small delay before the value is updated. Do you, @javierarce?

**Comment by javierarce** [comment]
I haven't noticed it, but I would venture to say that the recursive `deepSearch` could be the one causing the delay.

**Comment by damagedgoods** [comment]
I added a new artboard to the tester with +250 formula layers and I think the performance is (not great, but) ok. Can you try, @javierarce?

**Comment by javierarce** [comment]
I'm not sure how we could improve the speed, but I think right now it's acceptable.
